# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.4.0"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.5/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]
    [notes.qemu-guest-agent]
        title = "QEMU Guest Agent"
        description = """\
QEMU Guest Agent is now supported as Talos System Extension. Requires Talos v1.5.0 or later.
"""

    [notes.tailscale]
        title = "Tailscale"
        description = """\
Tailscale is now supported as Talos System Extension. Requires Talos v1.5.0 or later.
"""

    [notes.zfs]
        title = "ZFS"
        description = """\
ZFS is now supported as Talos System Extension. Requires Talos v1.5.0 or later.
"""

    [notes.thunderbolt]
        title = "Thunderbolt"
        description = """\
Thunderbolt drivers is now supported as Talos System Extension. Requires Talos v1.5.0 or later.
"""

    [notes.nvidia-kmod]
        title = "NVIDIA Non-Free Kernel Module"
        description = """\
NVIDIA non-free kernel modules are now supported as Talos System Extension. Requires Talos v1.5.0 or later.
"""

    [notes.updates]
        title = "Component Updates"
        description = """\
* Linux firmware: 20230804
* DRBD: 9.2.4
* Intel ucode: 20230808
* Open iSCSI: 2.1.9
* NVIDIA drivers: 535.54.03
* nvidia-container-toolkit: v1.13.5
* libnvidia-container: v1.13.5
"""


[make_deps]
